version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_USER: your_username_here
      POSTGRES_DB: your_database_name_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
